title: Technology and Stuff
author: John Simmons
email: John Simmons
description: > # this means to ignore newlines until "baseurl:"
  A place for an eclectic technology blog.

# social links
twitter_username: your-twitter-handle
github_username:  jsimmons2008

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
