title: My Tech Journey
author: John Simmons
email: jsimmons2008@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place to find the musings of a technologist that wants to rebrand himself.

# social links
twitter_username: your-twitter-handle
github_username:  jsimmons2008

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-midnight
